### ISSUE TITLE
NAGL won't charge single ions

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-nagl#138]
Not so much a bug as how best to communicate / prevent issues -- the naglrc3 model was not trained with single ions and does not accept single atoms with 0 bonds as an input feature (bond connectivity is one-hot encoded).

The easiest way to deal with this would be to just return the formal charge for a single ion. However, NAGL is meant to be a lot more agnostic than that -- e.g. you should be able to fit any atom property right now and down the line it should permit fitting and predicting bond properties.

Currently an error is raised, but eventually I imagine we'll want to seamlessly handle charging an entire system of protein + ligand + solvent + ions. Where should this happen? `Toolkit.assign_partial_charges` seems the simplest to me, but as #136 and https://github.com/openforcefield/openff-toolkit/issues/1587 show, we currently somewhat support combined separate molecules and some workflows may rely on that.

Could the saved model itself somehow specify a pre-processing step? That seems tricky at the moment, although somewhat feasible as it's currently just a pickle...

**Comment by lilyminium** [comment]
Well, actually, if I remade the model to include 0 bonds as a one-hot encoding I think the single ion charge should fall out of the total constraint at the end. Maybe that's the real answer.

**Comment by mrshirts** [comment]
Hah, I noticed this as well.  I went it and gave it the charge manually.  This should be fixed eventually, but I defer @lilyminium on the right ways to do it.   What you point out below sounds like it would be reasonable!

**Comment by lilyminium** [comment]
Maybe not the best solution but it wound up being easiest to hack the rc3 model and manually add an extra column to accept the 0 bonds as an input feature. #146 contains tests to check that this doesn't affect the charges of real molecules (as well as some technical fixes so NAGL can feasibly work with 0 bonds).
