### ISSUE TITLE
Cannot create TrainingGNNModel if ReadoutModule postprocessing is None

### ISSUE THREAD

**Issue by BenCree** [openforcefield/openff-nagl#155]
Hi,

## Expected behavior ##
In the [docs](https://docs.openforcefield.org/projects/nagl/en/stable/api/generated/openff.nagl.nn.ReadoutModule.html) it states that ReadoutModule posesses an 'optional postprocess layer'. More generally, I want to omit (charge) postprocessing to try to predict torsion 'energies' for bonds, instead of partial charges for atoms (or implement my own postprocessing specific to torsions). Any help would be appreciated.

## Actual behavior ##
Using the [train-gnn-notebook](https://github.com/openforcefield/openff-nagl/blob/main/examples/train-gnn-notebook/train-gnn-notebook.ipynb), setting postprocess=None (cell 4) results in an error creating TrainingGNNModel in cell 10:

`from openff.nagl.training.training import TrainingGNNModel, DGLMoleculeDataModule

training_model = TrainingGNNModel(training_config)
data_module = DGLMoleculeDataModule(training_config)`

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[11], line 3
      1 from openff.nagl.training.training import TrainingGNNModel, DGLMoleculeDataModule
----> 3 training_model = TrainingGNNModel(training_config)
      4 data_module = DGLMoleculeDataModule(training_config)

File [~/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/training/training.py:41](http://localhost:8888/lab/tree/code/openff-nagl/examples/train-gnn-notebook/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/training/training.py#line=40), in TrainingGNNModel.__init__(self, config)
     38 self.save_hyperparameters({"config": config.dict()})
     39 self.config = config
---> 41 self.model = GNNModel(config.model)
     42 self._data_config = {
     43     "train": self.config.data.training,
     44     "val": self.config.data.validation,
     45     "test": self.config.data.test,
     46 }

File [~/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/nn/_models.py:101](http://localhost:8888/lab/tree/code/openff-nagl/examples/train-gnn-notebook/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/nn/_models.py#line=100), in GNNModel.__init__(self, config, chemical_domain, lookup_tables)
     99 readout_modules = {}
    100 for readout_name, readout_config in config.readouts.items():
--> 101     readout_modules[readout_name] = ReadoutModule.from_config(
    102         readout_config,
    103         n_input_features=config.convolution.layers[-1].hidden_feature_size,
    104     )
    106 valid_lookup_tables = {}
    107 if not lookup_tables:

File [~/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/nn/_containers.py:197](http://localhost:8888/lab/tree/code/openff-nagl/examples/train-gnn-notebook/mambaforge/envs/nagl/lib/python3.12/site-packages/openff/nagl/nn/_containers.py#line=196), in ReadoutModule.from_config(cls, readout_config, n_input_features)
    186     layer_dropout.append(0.0)
    188 readout_layers = SequentialLayers.with_layers(
    189     n_input_features,
    190     hidden_feature_sizes,
    191     layer_activation_functions,
    192     layer_dropout,
    193 )
    194 return cls(
    195     pooling_layer,
    196     readout_layers,
--> 197     postprocess_layer
    198 )

UnboundLocalError: cannot access local variable 'postprocess_layer' where it is not associated with a value

## Code to reproduce the behavior ##

In cell 4:

`from openff.nagl.config.model import (
    ForwardLayer,
    ReadoutModule,
)

single_readout_layer = ForwardLayer(
    hidden_feature_size=128,  # 128 features per hidden convolution layer
    activation_function="ReLU", # max(0, x) activation function for layer
    dropout=0.0, # no dropout
)

readout_module = ReadoutModule(
    pooling="atoms",
    layers=[single_readout_layer] * 4, # 4 internal readout layers
    postprocess=None #postprocess="compute_partial_charges"
)`

## Current environment ##

- Which version are you using? 
0.4.0
- Which version of Python (`python -V`)? 
3.12.7
- Which operating system? Ubuntu 
22.04.4 LTS
- What is the output of `pip list`?

absl-py                   2.1.0
annotated-types           0.7.0
argcomplete               3.5.1
asttokens                 2.4.1
astunparse                1.6.3
attrs                     24.2.0
basis_set_exchange        0.10
Brotli                    1.1.0
bson                      0.5.9
cached-property           1.5.2
cachetools                5.5.0
certifi                   2024.8.30
cffi                      1.17.1
chardet                   5.2.0
charset-normalizer        3.4.0
click                     8.1.7
click-option-group        0.5.6
cloudpickle               3.1.0
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.0
cycler                    0.12.1
cytoolz                   1.0.0
dask                      2024.10.0
dask-jobqueue             0.9.0
debugpy                   1.8.7
decorator                 5.1.1
dgl                       2.1.0
distributed               2024.10.0
exceptiongroup            1.2.2
executing                 2.1.0
filelock                  3.16.1
flatbuffers               24.3.25
fonttools                 4.54.1
freetype-py               2.3.0
fsspec                    2024.10.0
gast                      0.5.5
gmpy2                     2.1.5
google-pasta              0.2.0
greenlet                  3.1.1
grpcio                    1.62.2
h2                        4.1.0
h5py                      3.12.1
hpack                     4.0.0
hyperframe                6.0.1
idna                      3.10
importlib_metadata        8.5.0
importlib_resources       6.4.5
ipykernel                 6.29.5
ipython                   8.29.0
jedi                      0.19.1
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.3
jupyter_core              5.7.2
keras                     3.6.0
kiwisolver                1.4.7
lightning-utilities       0.11.8
locket                    1.0.0
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                3.0.2
matplotlib                3.9.2
matplotlib-inline         0.1.7
mdurl                     0.1.2
ml-dtypes                 0.4.0
mpmath                    1.3.0
msgpack                   1.1.0
munkres                   1.1.4
namex                     0.0.8
nest_asyncio              1.6.0
networkx                  3.4.2
numpy                     1.26.4
openff-amber-ff-ports     0+untagged.32.g809f411.dirty
openff-interchange        0.3.29
openff-models             0.1.2
openff-nagl               0.4.0
openff-nagl-models        0.3.0
openff-qcsubmit           0.53.0
openff-recharge           0.5.2
openff-toolkit            0.16.5
openff-units              0.2.2
openff-utilities          0.1.12
openforcefields           2024.9.0
opt_einsum                3.4.0
optree                    0.13.0
packaging                 24.1
pandas                    2.2.3
parso                     0.8.4
partd                     1.4.2
pexpect                   4.9.0
pickleshare               0.7.5
pillow                    11.0.0
Pint                      0.23
pip                       24.2
pkgutil_resolve_name      1.3.10
platformdirs              4.3.6
prompt_toolkit            3.0.48
protobuf                  4.25.3
psutil                    6.1.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pyarrow                   17.0.0
pycairo                   1.27.0
pycparser                 2.22
pydantic                  2.9.2
pydantic_core             2.23.4
Pygments                  2.18.0
PyJWT                     2.9.0
pyparsing                 3.2.0
PySocks                   1.7.1
python-constraint         1.4.0
python-dateutil           2.9.0
pytorch-lightning         2.4.0
pytz                      2024.1
PyYAML                    6.0.2
pyzmq                     26.2.0
qcelemental               0.28.0
qcportal                  0.54.1
rdkit                     2024.9.1
referencing               0.35.1
regex                     2024.9.11
reportlab                 4.2.5
requests                  2.32.3
rich                      13.9.3
rlPyCairo                 0.2.0
rpds-py                   0.20.0
scipy                     1.14.1
setuptools                75.1.0
six                       1.16.0
smirnoff99frosst          0+unknown
sortedcontainers          2.4.0
SQLAlchemy                2.0.36
stack-data                0.6.2
sympy                     1.13.3
tabulate                  0.9.0
tblib                     3.0.0
tensorboard               2.17.1
tensorboard_data_server   0.7.0
tensorflow                2.17.0
tensorflow_estimator      2.15.0
termcolor                 2.5.0
toolz                     1.0.0
torch                     2.3.1
torchdata                 0.7.1+6427ed9
torchmetrics              1.5.1
tornado                   6.4.1
tqdm                      4.66.6
traitlets                 5.14.3
typing_extensions         4.12.2
tzdata                    2024.2
unicodedata2              15.1.0
Unidecode                 1.3.8
urllib3                   2.2.3
wcwidth                   0.2.13
Werkzeug                  3.0.6
wheel                     0.44.0
wrapt                     1.16.0
xmltodict                 0.14.2
zict                      3.0.0
zipp                      3.20.2
zstandard                 0.23.0

- If you use conda, what is the output of `conda list`?
# packages in environment at /home/cree/mambaforge/envs/nagl:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
argcomplete               3.5.1              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_2    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.31               h57bd9a3_0    conda-forge
aws-c-cal                 0.7.4                hfd43aa1_1    conda-forge
aws-c-common              0.9.28               hb9d3cd8_0    conda-forge
aws-c-compression         0.2.19               h756ea98_1    conda-forge
aws-c-event-stream        0.4.3                h29ce20c_2    conda-forge
aws-c-http                0.8.10               h5e77a74_0    conda-forge
aws-c-io                  0.14.18             h2af50b2_12    conda-forge
aws-c-mqtt                0.10.7               h02abb05_0    conda-forge
aws-c-s3                  0.6.6                h834ce55_0    conda-forge
aws-c-sdkutils            0.1.19               h756ea98_3    conda-forge
aws-checksums             0.1.20               h756ea98_0    conda-forge
aws-crt-cpp               0.28.3               h3e6eb3e_6    conda-forge
aws-sdk-cpp               1.11.379            h9f1560d_11    conda-forge
azure-core-cpp            1.13.0               h935415a_0    conda-forge
azure-identity-cpp        1.8.0                hd126650_2    conda-forge
azure-storage-blobs-cpp   12.12.0              hd2e3451_0    conda-forge
azure-storage-common-cpp  12.7.0               h10ac4d7_1    conda-forge
azure-storage-files-datalake-cpp 12.11.0              h325d260_1    conda-forge
basis_set_exchange        0.10               pyhd8ed1ab_1    conda-forge
brotli                    1.1.0                hb9d3cd8_2    conda-forge
brotli-bin                1.1.0                hb9d3cd8_2    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bson                      0.5.9                      py_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.5.0              pyhd8ed1ab_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
chardet                   5.2.0           py312h7900ff3_2    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-option-group        0.5.6              pyhd8ed1ab_0    conda-forge
cloudpickle               3.1.0              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0           py312h68727a3_2    conda-forge
cpython                   3.12.7          py312hd8ed1ab_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cytoolz                   1.0.0           py312h66e93f0_1    conda-forge
dask-core                 2024.10.0          pyhd8ed1ab_0    conda-forge
dask-jobqueue             0.9.0              pyhd8ed1ab_0    conda-forge
debugpy                   1.8.7           py312h2ec8cdc_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dgl                       2.1.0           py312h0c974e3_2    conda-forge
distributed               2024.10.0          pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.3                h5888daf_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
flatbuffers               24.3.25              h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.54.1          py312h178313f_1    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
fsspec                    2024.10.0          pyhff2d567_0    conda-forge
gast                      0.5.5              pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             h5888daf_1005    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py312h7201bc8_2    conda-forge
google-pasta              0.2.0              pyhd8ed1ab_1    conda-forge
greenlet                  3.1.1           py312h2ec8cdc_0    conda-forge
grpcio                    1.62.2          py312hb06c811_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.12.1          nompi_py312hedeef09_102    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.29.0             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
keras                     3.6.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.7           py312h68727a3_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarrow                  17.0.0          h200f1f0_15_cpu    conda-forge
libarrow-acero            17.0.0          h5888daf_15_cpu    conda-forge
libarrow-dataset          17.0.0          h5888daf_15_cpu    conda-forge
libarrow-substrait        17.0.0          hf54134d_15_cpu    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libboost                  1.86.0               hb8260a3_2    conda-forge
libboost-python           1.86.0          py312hc39e661_2    conda-forge
libbrotlicommon           1.1.0                hb9d3cd8_2    conda-forge
libbrotlidec              1.1.0                hb9d3cd8_2    conda-forge
libbrotlienc              1.1.0                hb9d3cd8_2    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgoogle-cloud           2.29.0               h435de7b_0    conda-forge
libgoogle-cloud-storage   2.29.0               h0121fbd_0    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
liblapacke                3.9.0           25_linux64_openblas    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_0    conda-forge
libparquet                17.0.0          h39682fd_15_cpu    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     16.4                 h2d7952a_3    conda-forge
libprotobuf               4.25.3               hd5b35b9_1    conda-forge
librdkit                  2024.09.1            h84b0b3c_3    conda-forge
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
libsodium                 1.0.20               h4ab18f5_0    conda-forge
libsqlite                 3.47.0               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libthrift                 0.20.0               h0e7cc3e_1    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libtorch                  2.3.1           cpu_generic_h970db74_0    conda-forge
liburing                  2.6                  h297d8ca_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.49.2               hb9d3cd8_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lightning-utilities       0.11.8             pyhd8ed1ab_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                3.0.2           py312h178313f_0    conda-forge
matplotlib-base           3.9.2           py312hd3ec401_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
metis                     5.1.1                h59595ed_2    conda-forge
ml_dtypes                 0.4.0           py312hf9745cd_2    conda-forge
mpc                       1.3.1                h24ddda3_1    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.1.0           py312h68727a3_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
namex                     0.0.8              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.4.2              pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numpy                     1.26.4          py312heda63a1_0    conda-forge
openff-amber-ff-ports     0.0.4              pyhca7485f_0    conda-forge
openff-forcefields        2024.09.0          pyhff2d567_0    conda-forge
openff-interchange-base   0.3.29             pyhd8ed1ab_0    conda-forge
openff-models             0.1.2              pyhca7485f_0    conda-forge
openff-nagl               0.4.0              pyhd8ed1ab_0    conda-forge
openff-nagl-base          0.4.0              pyhd8ed1ab_0    conda-forge
openff-nagl-models        0.3.0              pyhd8ed1ab_1    conda-forge
openff-qcsubmit           0.53.0             pyhd8ed1ab_1    conda-forge
openff-recharge           0.5.2              pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.16.5             pyhd8ed1ab_0    conda-forge
openff-units              0.2.2              pyhca7485f_0    conda-forge
openff-utilities          0.1.12             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
opt_einsum                3.4.0              pyhd8ed1ab_0    conda-forge
optree                    0.13.0          py312h68727a3_0    conda-forge
orc                       2.0.2                h669347b_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py312hf9745cd_1    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    11.0.0          py312h7b63e92_0    conda-forge
pint                      0.23               pyhd8ed1ab_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.48             pyha770c72_0    conda-forge
protobuf                  4.25.3          py312h83439f5_1    conda-forge
psutil                    6.1.0           py312h66e93f0_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   17.0.0          py312h9cebb41_1    conda-forge
pyarrow-core              17.0.0          py312h9cafe31_1_cpu    conda-forge
pycairo                   1.27.0          py312h51b637d_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.9.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.23.4          py312h12e396e_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.7          hc5c86c4_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-flatbuffers        24.3.25            pyh59ac667_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytorch                   2.3.1           cpu_generic_py312h2f1fc2b_0    conda-forge
pytorch-lightning         2.4.0              pyhd8ed1ab_0    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h66e93f0_1    conda-forge
pyzmq                     26.2.0          py312hbf22597_3    conda-forge
qcelemental               0.28.0             pyhd8ed1ab_1    conda-forge
qcportal                  0.54.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
rdkit                     2024.09.1       py312hd3b4007_3    conda-forge
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
regex                     2024.9.11       py312h66e93f0_0    conda-forge
reportlab                 4.2.5           py312h66e93f0_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.9.3             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.20.0          py312h12e396e_1    conda-forge
s2n                       1.5.5                h3931f03_0    conda-forge
scipy                     1.14.1          py312h62794b6_1    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.7                  h1b44611_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                2.0.36          py312h66e93f0_0    conda-forge
sqlite                    3.47.0               h9eae976_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.13.3           pyh2585a3b_104    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.17.1             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py312hda17c39_2    conda-forge
tensorflow                2.17.0          cpu_py312h69ecde4_2    conda-forge
tensorflow-base           2.17.0          cpu_py312h823dedb_2    conda-forge
tensorflow-estimator      2.17.0          cpu_py312h4f468f2_2    conda-forge
termcolor                 2.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     1.0.0              pyhd8ed1ab_0    conda-forge
torchdata                 0.7.1           py312he3f8c6c_7    conda-forge
torchmetrics              1.5.1              pyhe5570ce_0    conda-forge
tornado                   6.4.1           py312h66e93f0_1    conda-forge
tqdm                      4.66.6             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
unicodedata2              15.1.0          py312h66e93f0_1    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.6              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py312h66e93f0_1    conda-forge
xmltodict                 0.14.2             pyhd8ed1ab_0    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.5                h3b0a872_6    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by lilyminium** [comment]
Oops -- thanks for raising this, @BenCree. I'll look into this today

**Comment by lilyminium** [comment]
I opened #156 to fix the issue in the heading here. As to working with torsions, NAGL is in principle supposed to able to do this but unfortunately we haven't yet implemented torsion Janossy pooling yet into the pooling layers (and the bond one is very much untested and most likely doesn't work). It would be reasonably straightforward to do this but not quite sure when I can find time -- let me get back to you on that (or feel free to open a PR if you want to have a crack!)

**Comment by BenCree** [comment]
Sick. Cheers. As for Janossy pooling, I've not a scooby. I believe it should be straightforward, but that supposes a straightforward man. I hang out in the wriggly backrooms of thought. I'll give it a try.

**Comment by lilyminium** [comment]
Sure thing -- let me know how it goes or if I can help!
