### ISSUE TITLE
NAGL no longer raises forbidden pattern error for double bond to Cl+

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-nagl#160]
I just noticed that [this OFF Toolkit test](https://github.com/openforcefield/openff-toolkit/blame/8aa96bcc62b4815ee2ee6e29bd6316cb6135eab1/openff/toolkit/_tests/test_nagl.py#L142-L149) stopped raising the expected exception in openff-nagl 0.5.0. 

I see there were some changes to molecule sanitization since nagl 0.4 so maybe the intentionally malformed molecule now gets fixed internally. I'm having some trouble finding where the forbidden smarts are defined so I'd love either a pointer to that or a new molecule that raises an error.

**Comment by j-wags** [comment]
@lilyminium pointed out that the old molecule `C=[Cl+]` is now being handled by the lookup table, but `CCC=[Cl+]`, a trivial expansion of the molecule to make it too large for the lookup table, works for my purposes.

**Comment by lilyminium** [comment]
FYI for the future, each model has [a documentation page here](https://openff-nagl-models.readthedocs.io/en/latest/models/openff-gnn-am1bcc-0.1.0-rc3/index.html). I've raised an issue on the model repo as well as it's difficult to tell from the home page or README that these pages exist. https://github.com/openforcefield/openff-nagl-models/issues/37
