### ISSUE TITLE
Pyproject.toml leads to namespacing warning?

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-nagl#28]
## Expected behavior ##

No warnings show up when the package is loaded.

## Actual behavior ##

A warning:

```
In [1]: from openff.nagl.nn._models import GNNModel
/Users/mattthompson/mambaforge/envs/nagl/lib/python3.10/site-packages/lightning_utilities/core/imports.py:13: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-nagl is being added to sys.path
  import pkg_resources
```

## Code to reproduce the behavior ##

``` python
import openff.nagl
```

## Context

I think this is a namespacing error: https://stackoverflow.com/a/16787679/10247025

But, as far as I can tell, the `pyproject.toml` includes exactly the same information as `setup.py`, but the latter works and the former doesn't. 🤷‍♀️ This is a reminder to check back on this issue in the future.

Pyproject TOML: https://github.com/openforcefield/openff-nagl/blob/06e40fdce4e9e8a9846c7aa8b1e7b63cc42ed722/pyproject.toml
Setup.py: https://github.com/openforcefield/openff-nagl/blob/06e40fdce4e9e8a9846c7aa8b1e7b63cc42ed722/setup.py

**Comment by mattwthompson** [comment]
This confuses me a lot ... I spent a while trying to get this to work but haven't been able to. I stole what you did in #27 but it didn't work on my machine. I've at least been able to isolate the problem to when when `resource_filename` is imported, whether or not a `pyproject.toml` is present, which I guess happens at some point in your top-level `__init__.py`. This happens outside of this package whenever one of our packages has already been imported.

```python3
>>> import sys
>>> def f(): return [module for module in sys.modules.keys() if module.startswith("openff")]
...
>>> f()
[]
>>> import openff.toolkit
>>> f()
['openff', 'openff.toolkit._version', 'openff.toolkit']
>>> from pkg_resources import resource_filename
<stdin>:1: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-interchange is being added to sys.path
```

I imagine something would be borked if there was an `openff` package conflicting with our namespace packages, but that doesn't seem to be the case:
```
ls -lha /Users/mattthompson/mambaforge/envs/openff-interchange-env/lib/python3.10/site-packages/openff/
total 0
drwxr-xr-x    8 mattthompson  staff   256B Mar  6 11:11 .
drwxr-xr-x  526 mattthompson  staff    16K Mar  6 11:10 ..
drwxr-xr-x    8 mattthompson  staff   256B Mar  6 10:28 amber_ff_ports
drwxr-xr-x   22 mattthompson  staff   704B Mar  6 10:28 evaluator
drwxr-xr-x   10 mattthompson  staff   320B Mar  6 10:28 models
drwxr-xr-x   10 mattthompson  staff   320B Mar  6 10:28 toolkit
drwxr-xr-x   12 mattthompson  staff   384B Mar  6 10:28 units
drwxr-xr-x   12 mattthompson  staff   384B Mar  6 11:11 utilities
```
The cryptic error message (imported from `None`? what? isn't the point of `foo/bar` namespace modules that no `foo` namespace exists standalone?) makes me wonder if this is a bug in Setuptools. Are you able to configure things in a way that doesn't emit this warning on `from pkg_resources import resource_filename`? I don't opt in to PEP 517 so either that's not the root of the issue or there's a way to reproduce and fix it independent of `pyproject.toml` being present.

**Comment by lilyminium** [comment]
Iiiinteresting -- just to clarify, is this happening in an environment with NAGL installed, and did you reinstall without `pyproject.toml`? 

On a fresh environment with the `0.2.1` conda release (which should have #27 in it), I'm not able to reproduce:

```
$ conda create --name openff-nagl-release python=3.9
$ conda activate openff-nagl-release
$ mamba install -y -c conda-forge openff-nagl
$ conda list openff
# packages in environment at /Users/lily/anaconda3/envs/openff-nagl-release:
#
# Name                    Version                   Build  Channel
openff-amber-ff-ports     0.0.3              pyh6c4a22f_0    conda-forge
openff-forcefields        2023.02.1          pyh1a96a4e_0    conda-forge
openff-interchange        0.2.3              pyhd8ed1ab_1    conda-forge
openff-interchange-base   0.2.3              pyhd8ed1ab_1    conda-forge
openff-nagl               0.2.1              pyhd8ed1ab_0    conda-forge
openff-toolkit            0.12.1             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.12.1             pyhd8ed1ab_0    conda-forge
openff-units              0.2.0              pyh1a96a4e_0    conda-forge
openff-utilities          0.1.8              pyh1a96a4e_0    conda-forge
$ conda list setuptools
# packages in environment at /Users/lily/anaconda3/envs/openff-nagl-release:
#
# Name                    Version                   Build  Channel
setuptools                65.6.3           py39hecd8cb5_0
```

```python
>>> import sys
>>> def f(): return [module for module in sys.modules.keys() if module.startswith("openff")]
...
>>> f()
[]
>>> import openff.toolkit
>>> f()
['openff', 'openff.toolkit._version', 'openff.toolkit']
>>> from pkg_resources import resource_filename
>>>
```

In my dev environment I also managed to reproduce by checking out the repo before deleting `pyproject.toml` and re-installing, but couldn't reproduce after re-installing `main` again.
I do think this is from how `setuptools` in some way, although a quick skim of the egg-info looks roughly the same.

**Comment by mattwthompson** [comment]
Sorry, no, this is in my Interchange environment with Interchange code; I yoinked your changes to your `setup.cfg` file and it didn't fix it for my setup as it did for yours. I find that a little surprising since we're probably pulling from the same `openff/` packages. Knowing that your changes (likely?) fix problems in a more isolated `openff-nagl` environment helps and indicates there's something that fixes it ... I'll see if I can pin it down later.

All this being said - we should probably find a different way to get those file paths now: https://github.com/pypa/setuptools/pull/3843

**Comment by lilyminium** [comment]
The toolkit recently updated to use pyproject.toml -- time to revive this issue?

**Comment by mattwthompson** [comment]
```console
$ micromamba create --name nagl-28 "openff-nagl =0.5" "openff-toolkit ==0.16.7" -c conda-forge -yq && micromamba activate nagl-28
warning  libmamba [xorg-libx11-1.8.10-h6a5fb8c_1] The following files were already present in the environment:
    - include/X11/Xlib.h
    - include/X11/Xutil.h
    - include/X11/cursorfont.h
warning  libmamba [openff-interchange-base-0.4.0-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.12/site-packages/docs/conf.py
$ python
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:19:53) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openff.nagl.nn._models import GNNModel
>>>
```

This import took a while, I assume because of whatever compiling-ish stuff happens on the first startup in a fresh environment

**Comment by lilyminium** [comment]
Hm, I wonder if the environment would test for this -- due to the warnings I removed the pyproject.toml file from nagl in favour of the older setup.py and it doesn't look like the toolkit's pyproject.toml has made its way into a release yet. Regardless this issue was poorly named, I've opened a new one: #168

**Comment by lilyminium** [comment]
> This import took a while, I assume because of whatever compiling-ish stuff happens on the first startup in a fresh environment

That's not great, maybe I should bump up #58
