### ISSUE TITLE
Link to docs in README?

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-nagl#63]
I was poking around looking for a docs link and it took a couple clicks to end up there from the repo's webpage. Now that docs exist for the project, could there be the canonical "click here for docs" link added into the README? (I'm lazy.)

The same link could also go in this bit on the landing page:
![image](https://github.com/openforcefield/openff-nagl/assets/7935382/3926be4a-7b5e-4de8-8647-e76bdc0cc43a)

I also wonder if it's better to have the detailed installation instructions in the README in addition to those in the docs. Of course they're the same right now, but this could diverge in the future.

**Comment by lilyminium** [comment]
Thanks Matt, just added a link and pointed installation instructions to the main docs!

**Comment by lilyminium** [comment]
(I hope I understood you correctly that you thought it was an issue that they might diverge in the future and that one source of truth was best!)

**Comment by mattwthompson** [comment]
Yup, thanks, that's exactly it!
