### ISSUE TITLE
Charge assignment failing on macos with DGL backend

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-nagl#78]
## Expected behavior ##

Partial charge assignment using NAGL should work on macos.

## Actual behavior ##

Running NAGL on macos-latest runners on github actions leads to dgl related failures when assigning partial charges to a smile molecule (https://github.com/IAlibay/partial_charge_experiments/blob/main/datafiles/CN.sdf).

This seems to only occur when espaloma_charge is also installed, which I suspect is due to some issues with the DGL backend?

## Code to reproduce the behavior ##

Please see here for a minimum reproducing test & environment build: https://github.com/IAlibay/partial_charge_experiments/blob/main/scripts/run-nagl.py
Relevant test github action: https://github.com/IAlibay/partial_charge_experiments/blob/main/.github/workflows/run_nagl.yaml
Environment yaml file: https://github.com/IAlibay/partial_charge_experiments/blob/main/environment.yml
Failed action log: https://pipelinesghubeus13.actions.githubusercontent.com/oH1AYBkZ9c11jEMZOm6HI9jcT6n7DBF0SwZ2LjTfAKTA4XRGXL/_apis/pipelines/1/runs/13/signedlogcontent/2?urlExpires=2024-02-08T11%3A29%3A09.7335155Z&urlSigningMethod=HMACV1&urlSignature=7XFPXr0rRZUc%2FKXH%2Bly%2B8LRKY2A5aoj4hIM%2Fx%2BV%2Be6Y%3D

**Comment by lilyminium** [comment]
Thanks for raising this @IAlibay, tracked this down to a weird 2.0 incompatibility (that espaloma seems to be pulling in from dglteam's channel). I'll make a new release of NAGL pending some other small fixes soon!

**Comment by IAlibay** [comment]
Thanks @lilyminium 

To catch these things early - would it make sense to a) have a cron job running on your CI matrix to capture this early, b) bring up the range of runners on the CI matrix (i.e. go all the way to py3.12 if possible)?

**Comment by IAlibay** [comment]
Probably as an additional request (can open a separate issue) - more aggressive pinning on deployment would be good if possible. This would help ensure stability downstream.

**Comment by lilyminium** [comment]
Raising a separate issue would be helpful -- I'll get to more on this next week (there's also a CUDA bug I'd like to fix before the next release). In this particular case though a cron job wouldn't have been incredibly helpful since I was previously only checking conda-forge DGL, which is still on 1.x -- I imagine that's why your jobs were only failing with espaloma, which was pulling in 2.0 from pypi!
