### ISSUE TITLE
"future" Cron CI + expanding tested Python version

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/openff-nagl#84]
## Is your feature request related to a problem? ##

Since NAGL sits upstream of various things, it would be great if CI could catch issues as early as possible.

## Describe the solution you'd like ##

Some brief initial thoughts:

- Cron trigger on CI
- Pulling down from conda-forge & latest (maybe even develop, or nightly wheels) key upstream dependencies
- Expanding Cron CI to cover a wider range of python versions (3.12? see next issue)

**Comment by mattwthompson** [comment]
It's not the same thing, but throwing it into our ecosystem tests might catch some breaks?

https://github.com/openforcefield/status/pull/60
