### ISSUE TITLE
`train-multi-objective-gnn` and `train-gnn-notebook` notebooks failing on OpenFF Docs

### ISSUE THREAD

**Issue by Yoshanuikabundi** [openforcefield/openff-nagl#92]
I've gotten the OpenFF docs examples running again by manually skipping notebooks that were failing. This includes NAGL's `train-multi-objective-gnn` and `train-gnn-notebook` examples. Just dropping you a line to say that they don't seem to be working.

The environment used is here: https://github.com/openforcefield/openff-docs/blob/main/devtools/conda-envs/examples_env.yml

The list of skipped notebooks is here: https://github.com/openforcefield/openff-docs/blob/383a326bcae4154c9066b20aa925b407f288e14c/source/_ext/cookbook/globals_.py#L84

The goal is to set it up so that broken notebooks are automatically detected and don't block rendering other notebooks, but for now we're just manually specifying notebooks to skip.

**Comment by lilyminium** [comment]
I think this is fixed!
